php:
    container_name: php
    build: .
    ports: 
        - "80:80"
    volumes:
        - ./app:/var/www/html
    links: 
        - mariadb
        - redis

phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
        - mariadb
    ports:
        - 7070:80
    environment: 
        - PMA_ARBITRARY=1

mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    ports: 
        - "3307:3306"
    environment: 
        - MYSQL_ROOT_PASSWORD=google123
        - SERVICE_NAME=mysql
        
redis:
    container_name: redis
    image: redis